language: node_js
sudo: false
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nikita' ]; then cd .. && eval "mv $currentfolder generator-nikita" && cd generator-nikita; fi
before_deploy:
  - npm version $TRAVIS_TAG --no-git-tag-version
matrix:
  include:
    - node_js: '12.13.1'
      env: CXX=g++-4.8
    - node_js: '10.13.0'
      env: CXX=g++-4.8
    - node_js: '8.12.0'
      env:
        - TEMPLATE=web-app
        - CXX=g++-4.8
    - node_js: '8.12.0'
      env:
        - TEMPLATE=symfony
        - CXX=g++-4.8
    - node_js: '8.12.0'
      env:
        - TEMPLATE=wordpress
        - CXX=g++-4.8
    - node_js: '8.12.0'
      env:
        - TEMPLATE=spring-boot
        - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  skip_cleanup: true
  api_key:
    secure: b9/K16hOs/jdERiCPVH5PMqIY6x1f13pYxVyM+RJIr26luh6f1yPsABvJa/nCfCTFigOFlLiZA3h8hgGcDJFszccvyo4VaKnmoZyhe8Zbv5G8chLhwO0uhxnUghjLw9lpE3UCdFLBrV6cBDPpJ7CbUGS/grC++bRv+hQ33a78T0=
  on:
    tags: true
    repo: nikita-kit/generator-nikita
    all_branches: true
    node: 8.12.0
